azs:
- name: z1
  cloud_properties:
    availability_zone: ((terraform_outputs.az1))
- name: z2
  cloud_properties:
    availability_zone: ((terraform_outputs.az2))

vm_types:
- cloud_properties:
    instance_type: c6i.xlarge
    iam_instance_profile: ((terraform_outputs.bosh_compilation_profile))
    ephemeral_disk:
      size: 30000
    root_disk:
        size: 51200
  name: c6i.xlarge.compilation
- cloud_properties:
    instance_type: c6i.2xlarge
    ephemeral_disk:
      size: 15360
  name: c6i.2xlarge
- cloud_properties:
    instance_type: c6i.large
    ephemeral_disk:
      size: 15360
  name: c6i.large
- cloud_properties:
    instance_type: c6i.xlarge
    ephemeral_disk:
      size: 15360
  name: c6i.xlarge
- cloud_properties:
    instance_type: c6id.2xlarge
    ephemeral_disk:
      size: 15360
  name: c6id.2xlarge
- cloud_properties:
    instance_type: c6id.large
    ephemeral_disk:
      size: 15360
  name: c6id.large
- cloud_properties:
    instance_type: c6id.xlarge
    ephemeral_disk:
      size: 15360
  name: c6id.xlarge
- cloud_properties:
    instance_type: m5.large
    ephemeral_disk:
      size: 45000
  name: m5.large.concourse.web
- cloud_properties:
    instance_type: m5.xlarge
    ephemeral_disk:
      size: 300000
  name: m5.xlarge.concourse.worker
- cloud_properties:
    instance_type: m5.xlarge
    ephemeral_disk:
      size: 20000
  name: m5.xlarge.opsuaa
- cloud_properties:
    instance_type: m5.xlarge
    ephemeral_disk:
      size: 20000
  name: m5.xlarge.bosh.director
- cloud_properties:
    instance_type: m6i.2xlarge
    ephemeral_disk:
      size: 15360
  name: m6i.2xlarge
- cloud_properties:
    instance_type: m6i.large
    ephemeral_disk:
      size: 15360
  name: m6i.large
- cloud_properties:
    ephemeral_disk:
      size: 45000
    instance_type: m6i.large
  name: m6i.large.concourse.web
- cloud_properties:
    instance_type: m6i.xlarge
    ephemeral_disk:
      size: 15360
  name: m6i.xlarge
- cloud_properties:
    instance_type: m6i.xlarge
    ephemeral_disk:
      size: 20000
  name: m6i.xlarge.bosh.director
- cloud_properties:
    instance_type: m6i.xlarge
    ephemeral_disk:
      size: 300000
  name: m6i.xlarge.concourse.worker
- cloud_properties:
    instance_type: m6i.xlarge
    ephemeral_disk:
      size: 15360
  name: m6i.xlarge.opsuaa
- cloud_properties:
    instance_type: r5.xlarge
    ephemeral_disk:
      size: 30000
  name: r5.xlarge.logs_opensearch.ingestor
- cloud_properties:
    instance_type: r6i.2xlarge
    ephemeral_disk:
      size: 15360
  name: r6i.2xlarge
- cloud_properties:
    instance_type: r6i.4xlarge
    ephemeral_disk:
      size: 15360
  name: r6i.4xlarge
- cloud_properties:
    instance_type: r6i.8xlarge
    ephemeral_disk:
      size: 15360
  name: r6i.8xlarge
- cloud_properties:
    instance_type: r6i.large
    ephemeral_disk:
      size: 15360
  name: r6i.large
- cloud_properties:
    instance_type: r6i.xlarge
    ephemeral_disk:
      size: 15360
  name: r6i.xlarge
- cloud_properties:
    instance_type: t3.2xlarge
    ephemeral_disk:
      size: 15360
  name: t3.2xlarge
- cloud_properties:
    instance_type: t3.large
    ephemeral_disk:
      size: 15360
  name: t3.large
- cloud_properties:
    instance_type: t3.medium
    ephemeral_disk:
      size: 15360
  name: t3.medium
- cloud_properties:
    instance_type: t3.medium
    ephemeral_disk:
      size: 45000
  name: t3.medium.concourse.web
- cloud_properties:
    instance_type: t3.medium
    ephemeral_disk:
      size: 30000
  name: t3.medium.nessus.manager
- cloud_properties:
    instance_type: t3.micro
    ephemeral_disk:
      size: 15360
  name: t3.micro
- cloud_properties:
    instance_type: t3.nano
    ephemeral_disk:
      size: 15360
  name: t3.nano
- cloud_properties:
    instance_type: t3.small
    ephemeral_disk:
      size: 15360
  name: t3.small
- cloud_properties:
    instance_type: t3.xlarge
    ephemeral_disk:
      size: 15360
  name: t3.xlarge
- cloud_properties:
    instance_type: t3a.2xlarge
    ephemeral_disk:
      size: 15360
  name: t3a.2xlarge
- cloud_properties:
    instance_type: t3a.large
    ephemeral_disk:
      size: 15360
  name: t3a.large
- cloud_properties:
    instance_type: t3a.medium
    ephemeral_disk:
      size: 15360
  name: t3a.medium
- cloud_properties:
    instance_type: t3a.micro
    ephemeral_disk:
      size: 15360
  name: t3a.micro
- cloud_properties:
    instance_type: t3a.nano
    ephemeral_disk:
      size: 15360
  name: t3a.nano
- cloud_properties:
    instance_type: t3a.small
    ephemeral_disk:
      size: 15360
  name: t3a.small
- cloud_properties:
    instance_type: t3a.xlarge
    ephemeral_disk:
      size: 15360
  name: t3a.xlarge

vm_extensions:
- name: errand-profile
  cloud_properties:
    iam_instance_profile: ((terraform_outputs.bosh_compilation_profile))

networks: []
disk_types: []

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: c6i.xlarge.compilation
  az: z1
